import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Glob } from "bun";
import { extractMeta } from "../src/content/docs/meta";
import { sections } from "../src/content/docs/sections";

const DOCS_DIR = resolve(import.meta.dir, "../src/content/docs");
const SIDEBAR_PATH = resolve(import.meta.dir, "../src/content/docs/sidebar.ts");

interface DocMeta {
  title: string;
  description?: string;
  order?: number;
}

interface SidebarItem extends DocMeta {
  slug: string;
}

interface SidebarSection {
  title: string;
  items: SidebarItem[];
}

async function main() {
  const glob = new Glob("**/*.mdx");
  const slugToMeta = new Map<string, DocMeta>();

  // Read all MDX files and extract frontmatter
  for await (const file of glob.scan({ cwd: DOCS_DIR })) {
    const fullPath = resolve(DOCS_DIR, file);
    const content = readFileSync(fullPath, "utf-8");
    const meta = extractMeta(content);
    const slug = file.replace(/\.mdx$/, "");

    slugToMeta.set(slug, meta);
  }

  // Build sidebar sections
  const sidebarSections: SidebarSection[] = sections.map((section) => {
    const items: SidebarItem[] = section.slugs
      .map((slug) => {
        const meta = slugToMeta.get(slug);
        if (!meta || !meta.title) {
          console.error(`Warning: No frontmatter found for ${slug}`);
          return null;
        }
        return {
          slug,
          title: meta.title,
          description: meta.description,
          order: meta.order,
        };
      })
      .filter((item): item is NonNullable<typeof item> => item !== null)
      .sort((a, b) => {
        if (!a || !b) return 0;
        const orderA = a.order ?? 999;
        const orderB = b.order ?? 999;
        return orderA - orderB;
      }) as SidebarItem[];

    return {
      title: section.title,
      items,
    };
  });

  // Generate sidebar.ts content
  const output = `// Auto-generated by sync-sidebar.ts. Do not edit manually.
import type { DocMeta } from "./meta";

export interface SidebarItem extends DocMeta {
  slug: string;
}

export interface SidebarSection {
  title: string;
  items: SidebarItem[];
}

export const sections: SidebarSection[] = ${JSON.stringify(
    sidebarSections,
    null,
    2,
  )};

export const sidebar = sections.flatMap((section) => section.items);

const sidebarMap = new Map<string, { item: SidebarItem; index: number }>(
  sidebar.map((item, index) => [item.slug, { item, index }])
);

export function getDocBySlug(slug: string): SidebarItem | undefined {
  return sidebarMap.get(slug)?.item;
}

export function getPreviousDoc(slug: string): SidebarItem | undefined {
  const index = sidebarMap.get(slug)?.index;
  return index !== undefined && index > 0 ? sidebar[index - 1] : undefined;
}

export function getNextDoc(slug: string): SidebarItem | undefined {
  const index = sidebarMap.get(slug)?.index;
  return index !== undefined && index < sidebar.length - 1
    ? sidebar[index + 1]
    : undefined;
}
`;

  writeFileSync(SIDEBAR_PATH, output, "utf-8");
  console.log(`Generated sidebar.ts at ${SIDEBAR_PATH}`);

  // Stats
  const totalFiles = slugToMeta.size;
  const totalWithOrder = Array.from(slugToMeta.values()).filter(
    (m) => m.order !== undefined,
  ).length;
  console.log(`\nSummary:`);
  console.log(`  Total MDX files scanned: ${totalFiles}`);
  console.log(`  Files with order field: ${totalWithOrder}`);
}

main().catch((error) => {
  console.error("Error:", error);
  process.exit(1);
});
